title: SLSA
description: "SLSA: Security framework to ensure software supply chain integrity"
logo: /images/icons/android-chrome-512x512.png
repository: slsa-framework/slsa
baseurl: "/v1.0" # serves the URL with an additonal baseurl, for example, http://slsa.dev/v1.0.
destination: "./_site/v1.0" # stores the result in a specific directory.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/bundle
goatcounter:
  endpoint: https://slsa.goatcounter.com/count
theme: minima
permalink: :path/:basename
markdown: CommonMarkGhPages
commonmark:
  # UNSAFE needed to support raw HTML
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["autolink", "strikethrough", "table", "tagfilter"]
titles_from_headings:
  strip_title: true
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-sitemap
  - jekyll-seo-tag
  # Mandatory GitHub Pages plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
    values:
      layout: "specifications"
  - scope:
      path: ""
    values:
      # Set the Social image icon
      image: /images/icons/android-chrome-192x192.png
