# Redirect with a 301
[[redirects]]
from = "/spec/*"
to = "/:splat"

[[redirects]]
from = "/provenance/v1"
to = "/v1.0/provenance"

[[redirects]]
from = "/provenance/*"
to = "/:splat/provenance"

[[redirects]]
from = "/verification_summary/v1"
to = "/v1.0/verification_summary"

[[redirects]]
from = "/verification_summary/*"
to = "/:splat/verification_summary"

