# Redirect with a 301
[[redirects]]
from = "/spec/*"
to = "/:splat"

[[redirects]]
from = "/provenance/*"
to = "/:splat/provenance"

[[redirects]]
from = "/verification_summary/*"
to = "/:splat/verification_summary"
